version 2:
updates:
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "daily"
  pull-request-branch-name:
    separator: "_"
  target-branch: "dev"
  open-pull-requests-limit: 5
  allow:
  - dependency-type: "all"
  labels:
  - dependency
- package-ecosystem: "gitub-actions"
  directory: "/"
  schedule:
    interval: "daily"
  pull-request-branch-name:
    separator: "_"
  target-branch: "dev"
  open-pull-requests-limit: 5
  allow:
  - dependency-type: "all"
  labels:
  - dependency